#!/bin/bash

main()
{
	show_description
	dump_text_to_files
}

show_description()
{
cat <<EOF
    = Bits and Pieces =
    This exercise practices substring extraction and string manipulation.
    You are expected to complete the exercise, by using tr | cut | sed | grep.
EOF
}

dump_text_to_files()
{
    ROOT=$(mktemp --tmpdir=. -d)
    create_service_example_file
}

create_service_example_file()
{
    FILE=${ROOT}/service.xmpl
    DATA=( \
	'adam_2h-23m-21s_192.168.0.1_call,bridge' \
	'david_0h-2m-10s_192.169.0.2_call,bridge' \
	'john_1h-3m-1s_192.169.0.3_call' \
	'filip_2h-4m-45s_192.168.0.4_call,bridge,conference' \
	'susan_3h-34m-28s_192.165.0.3_call,music' \
	'ellie_5h-43m-49s_192.165.0.2_call,music,conference' \
	'michelle_1h-23m-21s_192.165.0.1_call' \
 	)
    OLD_IFS=${IFS}
    for data in ${DATA[*]}
    do
	IFS='_'
	printf "user:%s runtime:%s from:%s services:%s\n" ${data} >> ${FILE}
    done
    IFS=${OLD_IFS}
}

main