#!/bin/bash

main()
{
	show_description
	dump_text_to_files
}

show_description()
{
cat <<EOF
    = Bits and Pieces =
    This exercise practices substring extraction and string manipulation.
    You are expected to complete the exercise, by using tr | cut | sed | grep.
EOF
}

dump_text_to_files()
{
    ROOT=$(mktemp --tmpdir=. -d)
    create_service_example_file
}

create_service_example_file()
{
    FILE=${ROOT}/service.xmpl
    echo 'user:adam runtime:2h-23m-21s from:192.168.0.1 services:call,bridge' >> ${FILE}
    echo 'user:david runtime:0h-2m-10s from:192.169.0.2 services:call,bridge' >> ${FILE}
    echo 'user:john runtime:1h-3m-1s from:192.169.0.3 services:call' >> ${FILE}
    echo 'user:filip runtime:2h-4m-45s from:192.168.0.4 services:call,bridge,conference' >> ${FILE}
    echo 'user:susan runtime:3h-34m-28s from:192.165.0.3 services:call,music' >> ${FILE}
    echo 'user:ellie runtime:5h-43m-49s from:192.165.0.2 services:call,music,conference' >> ${FILE}
    echo 'user:michelle runtime:1h-23m-21s from:192.165.0.1 services:call' >> ${FILE}
    
}

main