#!/bin/bash

main()
{
    show_description
    create_directory_structure_with_files
    create_expected_listings
    show_the_expected_listings
    show_where_the_directory_structure_is_located
}

show_description()
{
cat <<EOF
    = Listings =
    This exercise will create a directory structure with files.
    Your goal is then to execute the ls command in such a way that the
    output matches the expected outputs in the different files shown
    below.

EOF
}

create_directory_structure_with_files()
{
    ROOT=$(mktemp -d --tmpdir=.)
    mkdir -p ${ROOT}/{a,b,c}{a,b,c}{a,b,c} &> /dev/null
    touch ${ROOT}/{a,b,c}{a,b,c}{a,b,c}/{a,b,c}{a,b,c}{a,b,c}.txt &> /dev/null
}

create_expected_listings()
{
    echo "     Created expected listings"
}

show_the_expected_listings()
{
    echo "    Show the expected listings"
}

show_where_the_directory_structure_is_located()
{
    echo "    Directory to run listings on ${ROOT}"
}

main