#!/bin/bash

main()
{
    show_description
    build_haystack
    insert_needles
    show_where_haystack_is_located
}

# ------------------------------------------------------------------------------
show_description()
{
cat <<EOF 
    = Needle in a haystack =
    This exercise will create a deep directory structure with many files.  
    Your goal is to find the files which match some specific criteria.
    The criteria will be given to you at the end of this text.

    = Criterias =
    File 1:  not writeable
             size of 10 B

    File 2:  is executable
	     smaller than the first file

    File 3:  contains the text 123
             is read only

    File 4:  contains the name of the file 

    = Setup progress = 
EOF
}

build_haystack()
{
    ROOT=$(mktemp --tmpdir=. -d)
    pushd ${ROOT} &> /dev/null
    for i in {1..10}
    do
	mktemp --tmpdir=. &> /dev/null
	mktemp --tmpdir=. -d &> /dev/null
	for i in tmp*/
	do
	    pushd ${i} &> /dev/null
	    mktemp --tmpdir=. &> /dev/null
	    NR=$(mktemp --tmpdir=. -d)
	    for i in {1..10}
	    do
		mktemp --tmpdir=${NR} &> /dev/null
	    done
	    popd &> /dev/null
	done
    done
    popd &> /dev/null
    echo "   * Built haystack"
}

insert_needles()
{
    for needle in {1..4}
    do
	pushd ${ROOT} &> /dev/null
	DEPTH=$((${RANDOM} % 2 ))
	for((i=0;i<${DEPTH};i++))
	do
	    DIRS=( tmp.*/ )
	    I=$(( ${RANDOM} % ${#DIRS[*]} ))
	    pushd ${DIRS[${I}]} &> /dev/null
	done
	make_needle_number ${needle} 
	for((i=0;i>${DEPTH};i++))
	do
	    popd &> /dev/null
	done
	popd &> /dev/null
    done
    echo "   * Needles inserted"
}

make_needle_number()
{
    case ${1} in
	1)
	    FILENAME=$(select_file_randomly)
	    echo "abcdefghi" > ${FILENAME}
	    chmod a-w ${FILENAME}
	    ;;
	2)
	    echo "needle 2"
	    ;;
	3)
	    echo "needle 3"
	    ;;
	4)
	    echo "needle 4"
	    ;;
    esac
}

select_file_randomly()
{
    FILES=( $(find . -maxdepth 1 -type f) )
    echo ${FILES[${RANDOM}%${#FILES[*]}]}
}

show_where_haystack_is_located()
{
    echo "showing"
}

main